version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/unifi-ddns-do/fw/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"